// GENERATED by tools/build_game.py from data/*.json — do not edit by hand.
const DATA = {
 "levelCap": 45,
 "statCurve": {
  "1": {
   "HP": 30,
   "PP": 14,
   "SP": 10,
   "ATK": 8,
   "SPATK": 6,
   "DEF": 7,
   "SPDEF": 6,
   "SPD": 9
  },
  "10": {
   "HP": 84,
   "PP": 24,
   "SP": 22,
   "ATK": 20,
   "SPATK": 18,
   "DEF": 18,
   "SPDEF": 17,
   "SPD": 20
  },
  "22": {
   "HP": 172,
   "PP": 44,
   "SP": 45,
   "ATK": 37,
   "SPATK": 38,
   "DEF": 34,
   "SPDEF": 34,
   "SPD": 35
  },
  "36": {
   "HP": 296,
   "PP": 72,
   "SP": 78,
   "ATK": 61,
   "SPATK": 66,
   "DEF": 56,
   "SPDEF": 58,
   "SPD": 55
  },
  "45": {
   "HP": 380,
   "PP": 90,
   "SP": 95,
   "ATK": 75,
   "SPATK": 80,
   "DEF": 70,
   "SPDEF": 72,
   "SPD": 68
  }
 },
 "moves": {
  "physical": [
   {
    "name": "Punch",
    "level": 1,
    "cost": 2,
    "power": 20,
    "hits": 1,
    "notes": "Baseline. Always affordable."
   },
   {
    "name": "Multi-Jab",
    "level": 6,
    "cost": 5,
    "power": 9,
    "hits": [
     2,
     4
    ],
    "notes": "Each hit rolls separately. Poor into high DEF."
   },
   {
    "name": "Wind-Up Punch",
    "level": 10,
    "cost": 9,
    "power": 34,
    "hits": 1,
    "priority": "last",
    "notes": "Always acts last regardless of SPD."
   },
   {
    "name": "Counter Stance",
    "level": 14,
    "cost": 6,
    "power": 0,
    "hits": 0,
    "notes": "Halves physical damage this turn; returns 50% of what was blocked."
   },
   {
    "name": "Gut Check",
    "level": 18,
    "cost": 8,
    "power": 30,
    "hits": 1,
    "notes": "40% chance to drop target ATK one stage."
   },
   {
    "name": "Haymaker",
    "level": 24,
    "cost": 14,
    "power": 48,
    "hits": 1,
    "accuracy": 0.8
   },
   {
    "name": "Rush Down",
    "level": 30,
    "cost": 12,
    "power": 24,
    "hits": 2,
    "priority": "first",
    "notes": "Second hit only lands if the first connects."
   },
   {
    "name": "Last Word",
    "level": 38,
    "cost": 20,
    "power": [
     36,
     72
    ],
    "hits": 1,
    "notes": "Power scales inversely with remaining HP. Max below 15%."
   }
  ],
  "special": [
   {
    "name": "Telekinesis",
    "level": 4,
    "cost": 3,
    "power": 22,
    "hits": 1,
    "notes": "First special learned."
   },
   {
    "name": "Mend",
    "level": 9,
    "cost": 6,
    "power": 0,
    "hits": 0,
    "heal_fraction": 0.35,
    "notes": "Only self-heal that is not an item."
   },
   {
    "name": "Health Steal",
    "level": 12,
    "cost": 7,
    "power": 26,
    "hits": 1,
    "drain_fraction": 0.5
   },
   {
    "name": "Mind Fog",
    "level": 16,
    "cost": 5,
    "power": 0,
    "hits": 0,
    "inflicts": "Fog"
   },
   {
    "name": "Static Pulse",
    "level": 20,
    "cost": 6,
    "power": 0,
    "hits": 0,
    "inflicts": "Static",
    "notes": "Also drops target SPD one stage."
   },
   {
    "name": "Aura Barrage",
    "level": 26,
    "cost": 13,
    "power": 17,
    "hits": 3,
    "target": "all"
   },
   {
    "name": "Quiet Room",
    "level": 31,
    "cost": 10,
    "power": 0,
    "hits": 0,
    "notes": "Halves special damage for 3 turns. The only cure for Homesick."
   },
   {
    "name": "Mend+",
    "level": 34,
    "cost": 12,
    "power": 0,
    "hits": 0,
    "heal_fraction": 0.7,
    "notes": "Also cures one status."
   },
   {
    "name": "Severance",
    "level": 40,
    "cost": 18,
    "power": 56,
    "hits": 1,
    "notes": "Ignores the target's SPDEF term entirely."
   },
   {
    "name": "Wake Up",
    "level": 43,
    "cost": 30,
    "power": 70,
    "hits": 1,
    "notes": "Learned immediately before the final area."
   }
  ]
 },
 "statuses": [
  {
   "name": "Static",
   "effect": "25% chance to lose the turn",
   "duration": 3,
   "item_curable": true,
   "player_effect": {
    "kind": "skip",
    "chance": 0.25
   },
   "enemy_effect": {
    "kind": "skip",
    "chance": 0.25
   }
  },
  {
   "name": "Fog",
   "effect": "-40% accuracy",
   "duration": 4,
   "item_curable": true,
   "player_effect": {
    "kind": "miss",
    "chance": 0.4
   },
   "enemy_effect": {
    "kind": "miss",
    "chance": 0.4
   }
  },
  {
   "name": "Drained",
   "effect": "PP/SP regen halved, SP costs +50%",
   "duration": 4,
   "item_curable": true,
   "player_effect": {
    "kind": "drain",
    "sp_cost_multiplier": 1.5,
    "regen_multiplier": 0.5,
    "why": "Halved, not stopped. Stopping it entirely recreates the exact lose-state the trickle exists to prevent - docs/05 says the player is never out of options, and a Drained player at 0 PP facing a boss they cannot flee has none. The trickle also never falls below the cheapest attack, so Punch is always payable."
   },
   "enemy_effect": {
    "kind": "weaken",
    "multiplier": 0.75
   }
  },
  {
   "name": "Numb",
   "effect": "DEF and SPDEF halved",
   "duration": 3,
   "item_curable": true,
   "player_effect": {
    "kind": "soften",
    "multiplier": 0.5
   },
   "enemy_effect": {
    "kind": "soften",
    "multiplier": 0.5
   }
  },
  {
   "name": "Homesick",
   "effect": "lose 5% max HP at end of turn",
   "duration": null,
   "item_curable": false,
   "player_effect": {
    "kind": "chip",
    "fraction": 0.05
   },
   "enemy_effect": null
  }
 ],
 "enemies": {
  "Yard Dog": {
   "level": 2,
   "role": "standard",
   "band": 1
  },
  "Postbox": {
   "level": 3,
   "role": "wall",
   "band": 1,
   "inaction_rate": 0.4
  },
  "Sunned Melon": {
   "level": 3,
   "role": "glass",
   "band": 1
  },
  "Little Cousin": {
   "level": 5,
   "role": "glass",
   "band": 1
  },
  "Fence Post": {
   "level": 6,
   "role": "brute",
   "band": 1,
   "inaction_rate": 0.6
  },
  "Windfall": {
   "level": 5,
   "role": "standard",
   "band": 2
  },
  "Drowned Ladder": {
   "level": 6,
   "role": "wall",
   "band": 2
  },
  "Same Tree": {
   "level": 7,
   "role": "standard",
   "band": 2
  },
  "Wader": {
   "level": 8,
   "role": "support",
   "band": 2,
   "inflicts": "Homesick"
  },
  "Orchard Keeper": {
   "level": 9,
   "role": "wall",
   "band": 2
  },
  "Milepost": {
   "level": 9,
   "role": "brute",
   "band": 3,
   "inaction_rate": 0.7
  },
  "Ration Tin": {
   "level": 10,
   "role": "standard",
   "band": 3,
   "drop_designed": true
  },
  "Someone's Bicycle": {
   "level": 11,
   "role": "glass",
   "band": 3
  },
  "Bad Weather": {
   "level": 12,
   "role": "standard",
   "band": 3
  },
  "Roadside Shrine": {
   "level": 13,
   "role": "support",
   "band": 3
  },
  "Frostbitten Glove": {
   "level": 11,
   "role": "support",
   "band": 4,
   "inflicts": "Numb"
  },
  "Coil": {
   "level": 13,
   "role": "glass",
   "band": 4,
   "inflicts": "Static"
  },
  "Conveyor": {
   "level": 14,
   "role": "standard",
   "band": 4
  },
  "Yard Light": {
   "level": 14,
   "role": "support",
   "band": 4,
   "inaction_rate": 0.7,
   "inflicts": "Fog"
  },
  "Second Shift": {
   "level": 15,
   "role": "brute",
   "band": 4
  },
  "Checkpoint": {
   "level": 15,
   "role": "wall",
   "band": 5
  },
  "Frozen Hare": {
   "level": 16,
   "role": "glass",
   "band": 5,
   "inaction_rate": 0.5
  },
  "Surplus Crate": {
   "level": 18,
   "role": "standard",
   "band": 5,
   "drop_designed": true
  },
  "Long Coat": {
   "level": 19,
   "role": "standard",
   "band": 5
  },
  "Commuter": {
   "level": 17,
   "role": "glass",
   "band": 6
  },
  "Kiosk": {
   "level": 18,
   "role": "standard",
   "band": 6
  },
  "Neon Sign": {
   "level": 19,
   "role": "glass",
   "band": 6,
   "inflicts": "Fog"
  },
  "Vixtry Canvasser": {
   "level": 21,
   "role": "standard",
   "band": 6
  },
  "Hall Mirror": {
   "level": 21,
   "role": "wall",
   "band": 7
  },
  "Tenant's Cat": {
   "level": 22,
   "role": "standard",
   "band": 7,
   "inaction_rate": 0.33
  },
  "Unit 4C": {
   "level": 24,
   "role": "wall",
   "band": 7,
   "inaction_rate": 1.0
  },
  "Mural": {
   "level": 25,
   "role": "standard",
   "band": 7
  },
  "Building Super": {
   "level": 26,
   "role": "brute",
   "band": 7
  },
  "Intern": {
   "level": 27,
   "role": "glass",
   "band": 8
  },
  "Receptionist": {
   "level": 28,
   "role": "support",
   "band": 8,
   "inflicts": "Drained"
  },
  "Demo Pod": {
   "level": 30,
   "role": "standard",
   "band": 8
  },
  "Server Rack": {
   "level": 31,
   "role": "wall",
   "band": 8
  },
  "Retention Specialist": {
   "level": 32,
   "role": "brute",
   "band": 8
  },
  "Ceiling Tile": {
   "level": 31,
   "role": "glass",
   "band": 9,
   "inaction_rate": 0.55
  },
  "Empty Frame": {
   "level": 33,
   "role": "standard",
   "band": 9
  },
  "Fluorescent": {
   "level": 34,
   "role": "standard",
   "band": 9,
   "inaction_rate": 0.5
  },
  "Custodial Cart": {
   "level": 36,
   "role": "brute",
   "band": 9
  },
  "Dresser": {
   "level": 40,
   "role": "wall",
   "band": 10
  },
  "Bedroom Door": {
   "level": 41,
   "role": "wall",
   "band": 10
  },
  "The Argument": {
   "level": 42,
   "role": "support",
   "band": 10,
   "inaction_rate": 1.0,
   "inflicts": "Homesick",
   "deals_damage": false
  }
 },
 "roles": {
  "standard": {
   "HP": 1.0,
   "ATK": 1.0,
   "DEF": 1.0,
   "SPD": 1.0
  },
  "brute": {
   "HP": 1.25,
   "ATK": 1.25,
   "DEF": 0.85,
   "SPD": 0.7
  },
  "wall": {
   "HP": 1.2,
   "ATK": 0.85,
   "DEF": 1.5,
   "SPD": 0.75,
   "why": " Raised in 0.5.0 alongside equipment: with a body slot in play, a role that barely hit stopped registering at all, and band 2 - which has two walls in five species - fell out of its attrition band. A wall is supposed to grind, not to be harmless."
  },
  "glass": {
   "HP": 0.65,
   "ATK": 1.2,
   "DEF": 0.6,
   "SPD": 1.45
  },
  "support": {
   "HP": 0.85,
   "ATK": 0.68,
   "DEF": 1.0,
   "SPD": 1.05,
   "why": " Raised in 0.5.0 alongside equipment: with a body slot in play, a role that barely hit stopped registering at all, and band 2 - which has two walls in five species - fell out of its attrition band. A wall is supposed to grind, not to be harmless."
  }
 },
 "enemyCurve": {
  "HP": {
   "base": 14,
   "per_level": 2.6,
   "per_level_squared": 0.65
  },
  "ATK": {
   "base": 3.36,
   "per_level": 0.688
  },
  "DEF": {
   "base": 2.8,
   "per_level": 0.8
  },
  "SPD": {
   "base": 4,
   "per_level": 1.1
  },
  "attack_power": 20
 },
 "bosses": {
  "The Fruiting Tree": {
   "role": "standard",
   "hp_multiplier": 2.35,
   "atk_multiplier": 0.98,
   "phases": 1
  },
  "The Memorial": {
   "role": "wall",
   "hp_multiplier": 2.97,
   "atk_multiplier": 1.17,
   "phases": 3,
   "tiers": {
    "count": 3,
    "why": "Fully defensive in tier 1, mixed in tier 2, desperate in tier 3. Absolute multipliers on the base stats, indexed by tier - not compounding, so the fight trades guard for urgency rather than simply getting harder.",
    "def_multiplier": [
     1.9,
     1.15,
     0.7
    ],
    "atk_multiplier": [
     0.45,
     0.85,
     1.2
    ]
   }
  },
  "Line Supervisor": {
   "role": "standard",
   "hp_multiplier": 2.28,
   "atk_multiplier": 1.3,
   "phases": 1,
   "self_buffs": 2
  },
  "Tenant": {
   "role": "standard",
   "hp_multiplier": 3.6,
   "atk_multiplier": 1.23,
   "phases": 3,
   "splits": true
  },
  "Account Manager": {
   "role": "support",
   "hp_multiplier": 2.49,
   "atk_multiplier": 1.36,
   "phases": 1,
   "inflicts": "Drained"
  },
  "The Custodian": {
   "role": "standard",
   "hp_multiplier": 2.9,
   "atk_multiplier": 1.36,
   "phases": 2,
   "restores_once_to": 0.5,
   "inflicts": "Homesick"
  },
  "Something Left Over": {
   "role": "brute",
   "hp_multiplier": 2.49,
   "atk_multiplier": 1.3,
   "phases": 1,
   "inflicts": "Homesick"
  },
  "The Custodian, Unfinished": {
   "role": "standard",
   "hp_multiplier": 3.82,
   "atk_multiplier": 1.41,
   "phases": 4,
   "inflicts": "Homesick",
   "damage_falloff_per_phase": 0.12
  }
 },
 "bossEncounters": {
  "The Fruiting Tree": {
   "internal_level": 10,
   "exp": 300,
   "act": 1,
   "drops": [
    "Tent Stake",
    "Spray II x3"
   ]
  },
  "The Memorial": {
   "internal_level": 16,
   "exp": 900,
   "act": 2,
   "drops": [
    "Anvil-Laden Sword",
    "Second Wind x1"
   ]
  },
  "Line Supervisor": {
   "internal_level": 20,
   "exp": 1200,
   "act": 3,
   "drops": [
    "Length of Pipe",
    "Work Jacket"
   ]
  },
  "Tenant": {
   "internal_level": 28,
   "exp": 2400,
   "act": 3,
   "drops": [
    "Signal Rod",
    "Full Spray x2"
   ]
  },
  "Account Manager": {
   "internal_level": 32,
   "exp": 2900,
   "act": 4,
   "drops": [
    "Foreman's Wrench",
    "Second Wind x2"
   ]
  },
  "The Custodian": {
   "internal_level": 36,
   "exp": 4000,
   "act": 4,
   "drops": [
    "Static Vest"
   ]
  },
  "Something Left Over": {
   "internal_level": 42,
   "exp": 4200,
   "act": 5,
   "drops": [
    "Quiet Instrument",
    "Full Spray x3"
   ]
  },
  "The Custodian, Unfinished": {
   "internal_level": 48,
   "exp": 0,
   "act": 5,
   "drops": []
  }
 },
 "items": {
  "Spray": {
   "price": 30,
   "effect": "restore 40 HP",
   "battle": true,
   "heal": 40,
   "field": true
  },
  "Spray II": {
   "price": 100,
   "effect": "restore 120 HP",
   "battle": true,
   "heal": 120,
   "field": true
  },
  "Spray III": {
   "price": 240,
   "effect": "restore 260 HP",
   "battle": true,
   "heal": 260,
   "field": true
  },
  "Full Spray": {
   "price": 600,
   "effect": "restore all HP",
   "battle": true,
   "heal": "full",
   "field": true
  },
  "Chalk Tablet": {
   "price": 60,
   "effect": "restore 25 PP",
   "battle": true,
   "pp": 25,
   "field": true
  },
  "Bitter Tonic": {
   "price": 60,
   "effect": "restore 25 SP",
   "battle": true,
   "sp": 25,
   "field": true
  },
  "Clean Rag": {
   "price": 25,
   "effect": "cure one status",
   "battle": true,
   "cure": true
  },
  "Knuckle Wrap": {
   "price": 70,
   "effect": "+1 ATK stage",
   "battle": true,
   "stage": 1,
   "stat": "atk",
   "at": "self"
  },
  "Cold Compress": {
   "price": 70,
   "effect": "+1 DEF stage",
   "battle": true,
   "stage": 1,
   "stat": "def",
   "at": "self"
  },
  "Thin Static": {
   "price": 80,
   "effect": "+1 SPATK stage",
   "battle": true,
   "stage": 1,
   "stat": "spatk",
   "at": "self"
  },
  "Wool Lining": {
   "price": 80,
   "effect": "+1 SPDEF stage",
   "battle": true,
   "stage": 1,
   "stat": "spdef",
   "at": "self"
  },
  "Loose Laces": {
   "price": 110,
   "effect": "+2 SPD stages",
   "battle": true,
   "stage": 2,
   "stat": "spd",
   "at": "self"
  },
  "Second Wind": {
   "price": 400,
   "effect": "+1 all stages",
   "battle": true,
   "stage": 1,
   "stat": "all",
   "at": "self"
  },
  "Dropped Call": {
   "price": 55,
   "effect": "inflict Fog",
   "battle": true,
   "inflict": "Fog"
  },
  "Loose Wire": {
   "price": 65,
   "effect": "inflict Static",
   "battle": true,
   "inflict": "Static"
  },
  "Dead Battery": {
   "price": 90,
   "effect": "inflict Drained",
   "battle": true,
   "inflict": "Drained"
  },
  "Shed Skin": {
   "price": 120,
   "effect": "-2 DEF stages",
   "battle": true,
   "stage": -2,
   "stat": "def",
   "at": "enemy"
  },
  "Letter": {
   "price": 0,
   "effect": "For someone on the north road.",
   "battle": false
  }
 },
 "damage": {
  "divisor": 12,
  "defCoeff": 0.5,
  "critChance": 0.04,
  "critMult": 1.75,
  "critPerSpd": 0.00025,
  "critMax": 0.22,
  "critPlayerOnly": true
 },
 "regen": {
  "PP": 2,
  "SP": 2,
  "HP": 0,
  "why": "Must be >= the cheapest move's cost (Punch, 2 PP) or the player alternates between acting and standing still."
 },
 "milestones": {
  "every": 10,
  "regen_bonus": 2,
  "why": "Every tenth level pays out twice: the PP/SP trickle goes up by a flat 2, and the player picks one of two passives. The trickle is the automatic half - it keeps late-game specials castable without touching their costs. The pick is the half the player owns, and it is the only place in the game where two runs at the same level are built differently.",
  "choices": {
   "10": [
    {
     "id": "steady_breathing",
     "name": "Steady Breathing",
     "effect": "Recover 5 HP at the start of every turn.",
     "kind": "hp_regen",
     "value": 5
    },
    {
     "id": "sharp_eye",
     "name": "Sharp Eye",
     "effect": "Criticals come 6% more often.",
     "kind": "crit_bonus",
     "value": 0.06
    }
   ],
   "20": [
    {
     "id": "thick_skin",
     "name": "Thick Skin",
     "effect": "Take 15% less damage.",
     "kind": "damage_taken",
     "value": 0.85
    },
    {
     "id": "long_reach",
     "name": "Long Reach",
     "effect": "Multi-hit moves land one extra hit 35% of the time.",
     "kind": "extra_hit",
     "value": 0.35
    }
   ],
   "30": [
    {
     "id": "clear_head",
     "name": "Clear Head",
     "effect": "Statuses on you wear off twice as fast.",
     "kind": "status_shed",
     "value": 2
    },
    {
     "id": "open_line",
     "name": "Open Line",
     "effect": "Specials cost 25% less SP.",
     "kind": "sp_discount",
     "value": 0.75
    }
   ],
   "40": [
    {
     "id": "follow_through",
     "name": "Follow Through",
     "effect": "A critical hits for 40% more on top.",
     "kind": "crit_followup",
     "value": 0.4
    },
    {
     "id": "last_word",
     "name": "Last Word",
     "effect": "Below a quarter HP, ATK and SPATK rise a stage.",
     "kind": "desperate",
     "value": 0.25
    }
   ]
  }
 },
 "equipment": {
  "Bare Hands": {
   "slot": "weapon",
   "act": 1,
   "price": 0,
   "stats": {},
   "flavour": "Yours. Cold at the knuckles."
  },
  "Tent Stake": {
   "slot": "weapon",
   "act": 1,
   "price": 150,
   "stats": {
    "atk": 3
   },
   "flavour": "Somebody camped here once and left in a hurry."
  },
  "Magic Baton": {
   "slot": "weapon",
   "act": 2,
   "price": 620,
   "stats": {
    "spatk": 5,
    "spd": 1
   },
   "flavour": "Light for its size. Warm at the grip, and it should not be."
  },
  "Anvil-Laden Sword": {
   "slot": "weapon",
   "act": 2,
   "price": 560,
   "stats": {
    "atk": 5,
    "def": 1,
    "spd": -4
   },
   "flavour": "Swinging it is a decision you commit to early."
  },
  "Length of Pipe": {
   "slot": "weapon",
   "act": 3,
   "price": 1400,
   "stats": {
    "atk": 7,
    "spd": -1
   },
   "flavour": "Threaded at one end. It came off something."
  },
  "Signal Rod": {
   "slot": "weapon",
   "act": 3,
   "price": 1650,
   "stats": {
    "atk": -2,
    "spatk": 9
   },
   "flavour": "It hums when you face a certain direction. You stop checking which."
  },
  "Foreman's Wrench": {
   "slot": "weapon",
   "act": 4,
   "price": 3000,
   "stats": {
    "atk": 11,
    "def": 2,
    "spd": -3
   },
   "flavour": "Initials filed off the handle. Not worn off — filed."
  },
  "Quiet Instrument": {
   "slot": "weapon",
   "act": 5,
   "price": 5200,
   "stats": {
    "atk": 4,
    "spatk": 12,
    "spd": 2
   },
   "flavour": "It makes no sound at all, and you can hear that it doesn't."
  },
  "School Clothes": {
   "slot": "body",
   "act": 1,
   "price": 0,
   "stats": {},
   "flavour": "Washed on a Sunday by someone who is not here."
  },
  "Patched Coat": {
   "slot": "body",
   "act": 1,
   "price": 200,
   "stats": {
    "def": 3,
    "spdef": 1
   },
   "flavour": "The patches are neater than the coat deserves."
  },
  "Fancy Suit": {
   "slot": "body",
   "act": 2,
   "price": 700,
   "stats": {
    "def": 2,
    "spdef": 5
   },
   "flavour": "Cut for someone half a head taller."
  },
  "Featherweight Coat": {
   "slot": "body",
   "act": 2,
   "price": 500,
   "stats": {
    "def": -2,
    "spd": 3
   },
   "flavour": "You keep checking you are still wearing it."
  },
  "Work Jacket": {
   "slot": "body",
   "act": 3,
   "price": 1500,
   "stats": {
    "def": 8,
    "spdef": 2,
    "spd": -1
   },
   "flavour": "A name tape, unpicked. The stitch holes are still there."
  },
  "Static Vest": {
   "slot": "body",
   "act": 4,
   "price": 3200,
   "stats": {
    "def": 1,
    "spdef": 10
   },
   "flavour": "Your hair stands up. It stays up."
  },
  "Lead Apron": {
   "slot": "body",
   "act": 4,
   "price": 2800,
   "stats": {
    "def": 14,
    "spdef": 6,
    "spd": -6
   },
   "flavour": "From somewhere that needed one."
  },
  "Overgrown Coat": {
   "slot": "body",
   "act": 5,
   "price": 0,
   "found": true,
   "stats": {
    "def": 6,
    "spdef": 6,
    "spd": 2,
    "hp": 20
   },
   "flavour": "Green."
  }
 },
 "equipStart": {
  "weapon": "Bare Hands",
  "body": "School Clothes"
 },
 "gearDrops": {
  "why": "Gear off a common enemy is the rarest thing in the drop table on purpose: it is a story about the world being full of other people's belongings, not a reliable way to shop. The pool is deliberately small and early - a late boss piece must still be earned.",
  "chance": 0.012,
  "pool": [
   "Magic Baton",
   "Patched Coat",
   "Featherweight Coat"
  ]
 },
 "drops": {
  "note": "What a defeated enemy leaves behind, on top of the Rell in docs/17. Rarity is keyed to price rather than to a hand-written tier list, so retuning an item's cost moves it through the table automatically and the two can never disagree about which things are precious.",
  "common_enemy": {
   "chance": 0.16,
   "why": "About one fight in six. Low enough that a drop is a small event, high enough that a player who grinds a corridor for ten minutes is paid for it. The tiers below decide what, given that something dropped.",
   "tiers": [
    {
     "tier": "common",
     "weight": 62,
     "max_price": 70,
     "why": "Sprays, tablets, rags, the cheap wraps. The floor of the table."
    },
    {
     "tier": "uncommon",
     "weight": 27,
     "max_price": 130,
     "why": "The better boosters and the first two debuffs."
    },
    {
     "tier": "rare",
     "weight": 10,
     "max_price": 700,
     "why": "Spray III, Second Wind. Worth stopping for."
    },
    {
     "tier": "gear",
     "weight": 1,
     "equipment": true,
     "why": "The pool in equipment.json. One drop in six hundred fights."
    }
   ]
  },
  "level_gate": {
   "why": "An enemy never drops something the player could not have been sold by now. Without this a level 3 rat in the first field can hand over a Spray III and flatten the whole early economy.",
   "price_per_level": 26,
   "floor": 60
  },
  "designed": {
   "why": "Two species exist to be opened rather than fought - docs/12 marks them drop_designed. They always drop, and they drop from one tier up.",
   "always_drops": true,
   "tier_shift": 1
  },
  "starting": {
   "weapon": "Bare Hands",
   "body": "School Clothes"
  },
  "gear": {
   "why": "Gear off a common enemy is the rarest thing in the drop table on purpose: it is a story about the world being full of other people's belongings, not a reliable way to shop. The pool is deliberately small and early - a late boss piece must still be earned.",
   "chance": 0.012,
   "pool": [
    "Magic Baton",
    "Patched Coat",
    "Featherweight Coat"
   ]
  }
 },
 "shopStock": {
  "1": [
   "Spray",
   "Clean Rag",
   "Tent Stake",
   "Patched Coat"
  ],
  "2": [
   "Spray",
   "Spray II",
   "Chalk Tablet",
   "Bitter Tonic",
   "Clean Rag",
   "Knuckle Wrap",
   "Cold Compress",
   "Dropped Call",
   "Magic Baton",
   "Anvil-Laden Sword",
   "Fancy Suit",
   "Featherweight Coat"
  ],
  "3": [
   "Spray II",
   "Spray III",
   "Chalk Tablet",
   "Bitter Tonic",
   "Clean Rag",
   "Knuckle Wrap",
   "Cold Compress",
   "Thin Static",
   "Wool Lining",
   "Loose Laces",
   "Dropped Call",
   "Loose Wire",
   "Dead Battery",
   "Shed Skin",
   "Length of Pipe",
   "Signal Rod",
   "Work Jacket"
  ],
  "4": [
   "Spray II",
   "Spray III",
   "Full Spray",
   "Chalk Tablet",
   "Bitter Tonic",
   "Clean Rag",
   "Thin Static",
   "Wool Lining",
   "Loose Laces",
   "Second Wind",
   "Dead Battery",
   "Shed Skin",
   "Foreman's Wrench",
   "Static Vest",
   "Lead Apron",
   "Quiet Instrument"
  ]
 },
 "currency": "Rell"
};
