// GENERATED by tools/build_game.py from data/*.json — do not edit by hand.
const DATA = {
 "levelCap": 45,
 "statCurve": {
  "1": {
   "HP": 30,
   "PP": 14,
   "SP": 10,
   "ATK": 8,
   "SPATK": 6,
   "DEF": 7,
   "SPDEF": 6,
   "SPD": 9
  },
  "10": {
   "HP": 84,
   "PP": 24,
   "SP": 22,
   "ATK": 20,
   "SPATK": 18,
   "DEF": 18,
   "SPDEF": 17,
   "SPD": 20
  },
  "22": {
   "HP": 172,
   "PP": 44,
   "SP": 45,
   "ATK": 37,
   "SPATK": 38,
   "DEF": 34,
   "SPDEF": 34,
   "SPD": 35
  },
  "36": {
   "HP": 296,
   "PP": 72,
   "SP": 78,
   "ATK": 61,
   "SPATK": 66,
   "DEF": 56,
   "SPDEF": 58,
   "SPD": 55
  },
  "45": {
   "HP": 380,
   "PP": 90,
   "SP": 95,
   "ATK": 75,
   "SPATK": 80,
   "DEF": 70,
   "SPDEF": 72,
   "SPD": 68
  }
 },
 "moves": {
  "physical": [
   {
    "name": "Punch",
    "level": 1,
    "cost": 2,
    "power": 20,
    "hits": 1,
    "notes": "Baseline. Always affordable."
   },
   {
    "name": "Multi-Jab",
    "level": 6,
    "cost": 5,
    "power": 9,
    "hits": [
     2,
     4
    ],
    "notes": "Each hit rolls separately. Poor into high DEF."
   },
   {
    "name": "Wind-Up Punch",
    "level": 10,
    "cost": 9,
    "power": 34,
    "hits": 1,
    "priority": "last",
    "notes": "Always acts last regardless of SPD."
   },
   {
    "name": "Counter Stance",
    "level": 14,
    "cost": 6,
    "power": 0,
    "hits": 0,
    "notes": "Halves physical damage this turn; returns 50% of what was blocked."
   },
   {
    "name": "Gut Check",
    "level": 18,
    "cost": 8,
    "power": 30,
    "hits": 1,
    "notes": "40% chance to drop target ATK one stage."
   },
   {
    "name": "Haymaker",
    "level": 24,
    "cost": 14,
    "power": 48,
    "hits": 1,
    "accuracy": 0.8
   },
   {
    "name": "Rush Down",
    "level": 30,
    "cost": 12,
    "power": 24,
    "hits": 2,
    "priority": "first",
    "notes": "Second hit only lands if the first connects."
   },
   {
    "name": "Last Word",
    "level": 38,
    "cost": 20,
    "power": [
     36,
     72
    ],
    "hits": 1,
    "notes": "Power scales inversely with remaining HP. Max below 15%."
   }
  ],
  "special": [
   {
    "name": "Telekinesis",
    "level": 4,
    "cost": 3,
    "power": 22,
    "hits": 1,
    "notes": "First special learned."
   },
   {
    "name": "Mend",
    "level": 9,
    "cost": 6,
    "power": 0,
    "hits": 0,
    "heal_fraction": 0.35,
    "notes": "Only self-heal that is not an item."
   },
   {
    "name": "Health Steal",
    "level": 12,
    "cost": 7,
    "power": 26,
    "hits": 1,
    "drain_fraction": 0.5
   },
   {
    "name": "Mind Fog",
    "level": 16,
    "cost": 5,
    "power": 0,
    "hits": 0,
    "inflicts": "Fog"
   },
   {
    "name": "Static Pulse",
    "level": 20,
    "cost": 6,
    "power": 0,
    "hits": 0,
    "inflicts": "Static",
    "notes": "Also drops target SPD one stage."
   },
   {
    "name": "Aura Barrage",
    "level": 26,
    "cost": 13,
    "power": 17,
    "hits": 3,
    "target": "all"
   },
   {
    "name": "Quiet Room",
    "level": 31,
    "cost": 10,
    "power": 0,
    "hits": 0,
    "notes": "Halves special damage for 3 turns. The only cure for Homesick."
   },
   {
    "name": "Mend+",
    "level": 34,
    "cost": 12,
    "power": 0,
    "hits": 0,
    "heal_fraction": 0.7,
    "notes": "Also cures one status."
   },
   {
    "name": "Severance",
    "level": 40,
    "cost": 18,
    "power": 56,
    "hits": 1,
    "notes": "Ignores the target's SPDEF term entirely."
   },
   {
    "name": "Wake Up",
    "level": 43,
    "cost": 30,
    "power": 70,
    "hits": 1,
    "notes": "Learned immediately before the final area."
   }
  ]
 },
 "statuses": [
  {
   "name": "Static",
   "effect": "25% chance to lose the turn",
   "duration": 3,
   "item_curable": true
  },
  {
   "name": "Fog",
   "effect": "-40% accuracy",
   "duration": 4,
   "item_curable": true
  },
  {
   "name": "Drained",
   "effect": "PP/SP regen suppressed, SP costs +50%",
   "duration": 4,
   "item_curable": true
  },
  {
   "name": "Numb",
   "effect": "DEF and SPDEF halved",
   "duration": 3,
   "item_curable": true
  },
  {
   "name": "Homesick",
   "effect": "lose 5% max HP at end of turn",
   "duration": null,
   "item_curable": false
  }
 ],
 "enemies": {
  "Yard Dog": {
   "level": 2,
   "role": "standard",
   "band": 1
  },
  "Postbox": {
   "level": 3,
   "role": "wall",
   "band": 1,
   "inaction_rate": 0.4
  },
  "Sunned Melon": {
   "level": 3,
   "role": "glass",
   "band": 1
  },
  "Little Cousin": {
   "level": 5,
   "role": "glass",
   "band": 1
  },
  "Fence Post": {
   "level": 6,
   "role": "brute",
   "band": 1,
   "inaction_rate": 0.6
  },
  "Windfall": {
   "level": 5,
   "role": "standard",
   "band": 2
  },
  "Drowned Ladder": {
   "level": 6,
   "role": "wall",
   "band": 2
  },
  "Same Tree": {
   "level": 7,
   "role": "standard",
   "band": 2
  },
  "Wader": {
   "level": 8,
   "role": "support",
   "band": 2,
   "inflicts": "Homesick"
  },
  "Orchard Keeper": {
   "level": 9,
   "role": "wall",
   "band": 2
  },
  "Milepost": {
   "level": 9,
   "role": "brute",
   "band": 3,
   "inaction_rate": 0.7
  },
  "Ration Tin": {
   "level": 10,
   "role": "standard",
   "band": 3
  },
  "Someone's Bicycle": {
   "level": 11,
   "role": "glass",
   "band": 3
  },
  "Bad Weather": {
   "level": 12,
   "role": "standard",
   "band": 3
  },
  "Roadside Shrine": {
   "level": 13,
   "role": "support",
   "band": 3
  },
  "Frostbitten Glove": {
   "level": 11,
   "role": "support",
   "band": 4,
   "inflicts": "Numb"
  },
  "Coil": {
   "level": 13,
   "role": "glass",
   "band": 4,
   "inflicts": "Static"
  },
  "Conveyor": {
   "level": 14,
   "role": "standard",
   "band": 4
  },
  "Yard Light": {
   "level": 14,
   "role": "support",
   "band": 4,
   "inaction_rate": 0.7,
   "inflicts": "Fog"
  },
  "Second Shift": {
   "level": 15,
   "role": "brute",
   "band": 4
  },
  "Checkpoint": {
   "level": 15,
   "role": "wall",
   "band": 5
  },
  "Frozen Hare": {
   "level": 16,
   "role": "glass",
   "band": 5,
   "inaction_rate": 0.5
  },
  "Surplus Crate": {
   "level": 18,
   "role": "standard",
   "band": 5
  },
  "Long Coat": {
   "level": 19,
   "role": "standard",
   "band": 5
  },
  "Commuter": {
   "level": 17,
   "role": "glass",
   "band": 6
  },
  "Kiosk": {
   "level": 18,
   "role": "standard",
   "band": 6
  },
  "Neon Sign": {
   "level": 19,
   "role": "glass",
   "band": 6,
   "inflicts": "Fog"
  },
  "Vixtry Canvasser": {
   "level": 21,
   "role": "standard",
   "band": 6
  },
  "Hall Mirror": {
   "level": 21,
   "role": "wall",
   "band": 7
  },
  "Tenant's Cat": {
   "level": 22,
   "role": "standard",
   "band": 7,
   "inaction_rate": 0.33
  },
  "Unit 4C": {
   "level": 24,
   "role": "wall",
   "band": 7,
   "inaction_rate": 1.0
  },
  "Mural": {
   "level": 25,
   "role": "standard",
   "band": 7
  },
  "Building Super": {
   "level": 26,
   "role": "brute",
   "band": 7
  },
  "Intern": {
   "level": 27,
   "role": "glass",
   "band": 8
  },
  "Receptionist": {
   "level": 28,
   "role": "support",
   "band": 8,
   "inflicts": "Drained"
  },
  "Demo Pod": {
   "level": 30,
   "role": "standard",
   "band": 8
  },
  "Server Rack": {
   "level": 31,
   "role": "wall",
   "band": 8
  },
  "Retention Specialist": {
   "level": 32,
   "role": "brute",
   "band": 8
  },
  "Ceiling Tile": {
   "level": 31,
   "role": "glass",
   "band": 9,
   "inaction_rate": 0.55
  },
  "Empty Frame": {
   "level": 33,
   "role": "standard",
   "band": 9
  },
  "Fluorescent": {
   "level": 34,
   "role": "standard",
   "band": 9,
   "inaction_rate": 0.5
  },
  "Custodial Cart": {
   "level": 36,
   "role": "brute",
   "band": 9
  },
  "Dresser": {
   "level": 40,
   "role": "wall",
   "band": 10
  },
  "Bedroom Door": {
   "level": 41,
   "role": "wall",
   "band": 10
  },
  "The Argument": {
   "level": 42,
   "role": "support",
   "band": 10,
   "inaction_rate": 1.0,
   "inflicts": "Homesick",
   "deals_damage": false
  }
 },
 "roles": {
  "standard": {
   "HP": 1.0,
   "ATK": 1.0,
   "DEF": 1.0,
   "SPD": 1.0
  },
  "brute": {
   "HP": 1.25,
   "ATK": 1.25,
   "DEF": 0.85,
   "SPD": 0.7
  },
  "wall": {
   "HP": 1.2,
   "ATK": 0.7,
   "DEF": 1.5,
   "SPD": 0.75
  },
  "glass": {
   "HP": 0.65,
   "ATK": 1.2,
   "DEF": 0.6,
   "SPD": 1.45
  },
  "support": {
   "HP": 0.85,
   "ATK": 0.55,
   "DEF": 1.0,
   "SPD": 1.05
  }
 },
 "enemyCurve": {
  "HP": {
   "base": 14,
   "per_level": 2.6,
   "per_level_squared": 0.65
  },
  "ATK": {
   "base": 3.36,
   "per_level": 0.688
  },
  "DEF": {
   "base": 2.8,
   "per_level": 0.8
  },
  "SPD": {
   "base": 4,
   "per_level": 1.1
  },
  "attack_power": 20
 },
 "bosses": {
  "The Fruiting Tree": {
   "role": "standard",
   "hp_multiplier": 1.48,
   "atk_multiplier": 0.98,
   "phases": 1
  },
  "The Memorial": {
   "role": "wall",
   "hp_multiplier": 1.78,
   "atk_multiplier": 1.17,
   "phases": 3,
   "tiers": {
    "count": 3,
    "why": "Fully defensive in tier 1, mixed in tier 2, desperate in tier 3. Absolute multipliers on the base stats, indexed by tier - not compounding, so the fight trades guard for urgency rather than simply getting harder.",
    "def_multiplier": [
     1.9,
     1.15,
     0.7
    ],
    "atk_multiplier": [
     0.45,
     0.85,
     1.2
    ]
   }
  },
  "Line Supervisor": {
   "role": "standard",
   "hp_multiplier": 1.63,
   "atk_multiplier": 1.3,
   "phases": 1,
   "self_buffs": 2
  },
  "Tenant": {
   "role": "standard",
   "hp_multiplier": 2.1,
   "atk_multiplier": 1.23,
   "phases": 3,
   "splits": true
  },
  "Account Manager": {
   "role": "support",
   "hp_multiplier": 1.78,
   "atk_multiplier": 1.36,
   "phases": 1,
   "inflicts": "Drained"
  },
  "The Custodian": {
   "role": "standard",
   "hp_multiplier": 2.07,
   "atk_multiplier": 1.36,
   "phases": 2,
   "restores_once_to": 0.5,
   "inflicts": "Homesick"
  },
  "Something Left Over": {
   "role": "brute",
   "hp_multiplier": 1.78,
   "atk_multiplier": 1.3,
   "phases": 1,
   "inflicts": "Homesick"
  },
  "The Custodian, Unfinished": {
   "role": "standard",
   "hp_multiplier": 2.5,
   "atk_multiplier": 1.41,
   "phases": 4,
   "inflicts": "Homesick",
   "damage_falloff_per_phase": 0.12
  }
 },
 "bossEncounters": {
  "The Fruiting Tree": {
   "internal_level": 10,
   "exp": 300,
   "act": 1
  },
  "The Memorial": {
   "internal_level": 16,
   "exp": 900,
   "act": 2
  },
  "Line Supervisor": {
   "internal_level": 20,
   "exp": 1200,
   "act": 3
  },
  "Tenant": {
   "internal_level": 28,
   "exp": 2400,
   "act": 3
  },
  "Account Manager": {
   "internal_level": 32,
   "exp": 2900,
   "act": 4
  },
  "The Custodian": {
   "internal_level": 36,
   "exp": 4000,
   "act": 4
  },
  "Something Left Over": {
   "internal_level": 42,
   "exp": 4200,
   "act": 5
  },
  "The Custodian, Unfinished": {
   "internal_level": 48,
   "exp": 0,
   "act": 5
  }
 },
 "items": {
  "Spray": {
   "price": 30,
   "effect": "restore 40 HP",
   "battle": true,
   "heal": 40,
   "field": true
  },
  "Spray II": {
   "price": 100,
   "effect": "restore 120 HP",
   "battle": true,
   "heal": 120,
   "field": true
  },
  "Spray III": {
   "price": 240,
   "effect": "restore 260 HP",
   "battle": true,
   "heal": 260,
   "field": true
  },
  "Full Spray": {
   "price": 600,
   "effect": "restore all HP",
   "battle": true,
   "heal": "full",
   "field": true
  },
  "Chalk Tablet": {
   "price": 60,
   "effect": "restore 25 PP",
   "battle": true,
   "pp": 25,
   "field": true
  },
  "Bitter Tonic": {
   "price": 60,
   "effect": "restore 25 SP",
   "battle": true,
   "sp": 25,
   "field": true
  },
  "Clean Rag": {
   "price": 25,
   "effect": "cure one status",
   "battle": true
  },
  "Knuckle Wrap": {
   "price": 70,
   "effect": "+1 ATK stage",
   "battle": true
  },
  "Cold Compress": {
   "price": 70,
   "effect": "+1 DEF stage",
   "battle": true
  },
  "Thin Static": {
   "price": 80,
   "effect": "+1 SPATK stage",
   "battle": true
  },
  "Wool Lining": {
   "price": 80,
   "effect": "+1 SPDEF stage",
   "battle": true
  },
  "Loose Laces": {
   "price": 110,
   "effect": "+2 SPD stages",
   "battle": true
  },
  "Second Wind": {
   "price": 400,
   "effect": "+1 all stages",
   "battle": true
  },
  "Dropped Call": {
   "price": 55,
   "effect": "inflict Fog",
   "battle": true
  },
  "Loose Wire": {
   "price": 65,
   "effect": "inflict Static",
   "battle": true
  },
  "Dead Battery": {
   "price": 90,
   "effect": "inflict Drained",
   "battle": true
  },
  "Shed Skin": {
   "price": 120,
   "effect": "-2 DEF stages",
   "battle": true
  },
  "Letter": {
   "price": 0,
   "effect": "For someone on the north road.",
   "battle": false
  }
 },
 "damage": {
  "divisor": 12,
  "defCoeff": 0.5,
  "critChance": 0.04,
  "critMult": 1.75,
  "critPerSpd": 0.00025,
  "critMax": 0.22,
  "critPlayerOnly": true
 },
 "regen": {
  "PP": 2,
  "SP": 2,
  "HP": 0,
  "why": "Must be >= the cheapest move's cost (Punch, 2 PP) or the player alternates between acting and standing still."
 },
 "shopStock": [
  "Spray",
  "Clean Rag",
  "Tent Stake",
  "Patched Coat"
 ],
 "currency": "Rell"
};
